networks:
  npnet:
    external: true

services:
  bot:
    build: .
    container_name: mmm-bot
    restart: unless-stopped
    env_file: .env
    expose:
      - "8001"
    networks:
      - npnet
    volumes:
      - ./trade.db:/app/bot/trade.db
      - ./social:/app/social
      - ./bot.log:/app/bot/bot.log

  agg-bot:
    build:
      context: .
      dockerfile: Dockerfile.agg
    container_name: mmm-agg-bot
    restart: unless-stopped
    env_file: .env
    networks:
      - npnet
    volumes:
      - ./agg.db:/app/agg-bot/agg.db

  ton-bot:
    build:
      context: .
      dockerfile: Dockerfile.ton
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./ton.db:/app/ton-bot/ton.db
